### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by web1919** [huan-cdm/info_scan#12]
可以出一个虚拟机的安装教程吗，大佬，配置都改了就是起不来

**Comment by huan-cdm** [comment]
参考readme文件和历史关闭的Issues中的问题，如果还未解决，请提供您的报错截图。
下载最新版的虚拟机：https://pan.quark.cn/s/81003c01a616#/list/share

**Comment by zh12ang** [comment]
我也是520报错，排查了好多就是起不来
