### ISSUE TITLE
导入sql文件夹目录下的sql文件报错

### ISSUE THREAD

**Issue by xiaoshengyyds** [huan-cdm/info_scan#14]
报错如下：
ERROR 1146 (42S02): Unknown error 1146
ERROR 1146 (42S02): Unknown error 1146
ERROR 1146 (42S02): Unknown error 1146
ERROR 1146 (42S02): Unknown error 1146
ERROR 1146 (42S02): Unknown error 1146
ERROR 1146 (42S02): Unknown error 1146
使用的是mysql5.7.36

**Comment by huan-cdm** [comment]
用navicat导入，测试没问题

**Comment by xiaoshengyyds** [comment]
> 用navicat导入，测试没问题
版本没影响吧，字符集有什么要求吗

**Comment by huan-cdm** [comment]
版本没要求，字符选utf8
![image](https://github.com/user-attachments/assets/e70c9103-1a02-4f22-9c66-697e0b203381)
可以选择虚拟机版本，直接下载就能用。

**Comment by xiaoshengyyds** [comment]
直接安装虚拟机也可以，但是这样的话如果大佬您这边更新项目了我是不是还得重新下载最新版的虚拟机，所以我感觉有点麻烦，就想自己搭建一下看看

**Comment by xiaoshengyyds** [comment]
是这些sql吧？
![image](https://github.com/user-attachments/assets/a3b262ff-c935-4c98-9b2c-525d43043eb0)

**Comment by huan-cdm** [comment]
是的
