### ISSUE TITLE
开始对目标进行端口或其他扫描的时候，出现内部错误提示

### ISSUE THREAD

**Issue by xiaoshengyyds** [huan-cdm/info_scan#15]
图片所示，多个模块的错误都是显示这个
![77b3f441e53d3b7972bf7fbbab58815e](https://github.com/user-attachments/assets/a33ca880-2ee0-4739-9b39-9b2c3b127e73)

**Comment by huan-cdm** [comment]
从截图看不出来是哪里报错的，这个report_total.report_xlsx是报告整合的函数，不是扫描相关的
config.py都配置下，扫描器部分也需要安装模块，可能是缺少模块，建议下载虚拟机，在那个上面迭代新版本。

**Comment by xiaoshengyyds** [comment]
就是开启全盘扫描的时候，调用工具开始扫描的时候就报这些self.xxxx类似这种报错；用的就是最新的虚拟机而不是自己安装的

**Comment by huan-cdm** [comment]
用root权限启动相关服务，config.py该配置的都配置上，我这边测试没有问题。

**Comment by xiaoshengyyds** [comment]
晚上回去给您这边演示下问题的错误现象和整体过程

**Comment by xiaoshengyyds** [comment]
首先，主系统中开启IP搜索没问题，我这里使用的是域名
![1728728237329](https://github.com/user-attachments/assets/1c23d90b-2e97-407a-9806-5bfb825c68c1)
然后，我现在开启模块搜索
![1728728383981](https://github.com/user-attachments/assets/2681d6f7-36de-4177-9c7a-ae8af3420e50)

**Comment by huan-cdm** [comment]
参考视频：
https://www.bilibili.com/video/BV1Gt28YFEr3
还是不行的话将你联系方式发到主页邮箱

**Comment by huan-cdm** [comment]
参考视频：
https://www.bilibili.com/video/BV1Gt28YFEr3
还是不行的话将你联系方式发我github主页邮箱
