### ISSUE TITLE
开启失败

### ISSUE THREAD

**Issue by xxxxxxovo** [huan-cdm/info_scan#3]
<img width="459" alt="Snipaste_2024-06-29_05-19-15" src="https://github.com/huan-cdm/info_scan/assets/142147430/c806e85f-c01d-4a06-8858-af9aa89eb3db">
服务开启失败
web也无法访问，请大佬解答

- <img width="691" alt="Snipaste_2024-06-29_05-21-16" src="https://github.com/huan-cdm/info_scan/assets/142147430/4165d418-c7aa-4aa7-b616-db014e8d6a00">

**Comment by huan-cdm** [comment]
查看server_check.sh中调用的py文件，运行py文件，缺哪个模块安装对应的模块即可。

**Comment by huan-cdm** [comment]
web是走的127.0.0.1；公网访问需要通过nginx做反向代理，nginx相关配置文件在nginx_conf目录下。

**Comment by ping401** [comment]
为什么进行扫描时报这个错误呢？
![Uploading Snipaste_2024-06-29_23-22-51.png…]()

**Comment by ping401** [comment]
为什么进行扫描时报这个错误呢？
<img width="735" alt="Snipaste_2024-06-29_23-22-51" src="https://github.com/huan-cdm/info_scan/assets/160581555/1e6f2ff3-20da-4f2c-a7df-33475ea05343">

**Comment by ping401** [comment]
环境好难配置啊，能搞个简单的不，尤其是Python 库，需要一个一个的去找缺了那些依赖。弄了半天了，然后运行还报错。。。5555555555555

**Comment by huan-cdm** [comment]
先别用shell脚本启动，先执行python3 scan_main_web启动，系统跑通在用shell脚本启动方便一些，每个功能都运行一遍，在控制台就能看见缺少的模块和报错信息，缺哪个安装哪个就行，系统所集成的扫描器也需要安装对应的模块，确保扫描器能正常运行就行。
还有问题的把报错信息贴上来。感谢大家！

**Comment by skilfulwriter** [comment]
![image](https://github.com/user-attachments/assets/381cc28d-69b3-460d-9db7-830c51b5d6d4)
![image](https://github.com/user-attachments/assets/0b938cee-87ba-4a29-85c8-157f4f8c6c9f)
请问一下这什么情况

**Comment by skilfulwriter** [comment]
![image](https://github.com/user-attachments/assets/a28ec0bc-ed4f-476d-908b-720c788ad8f8)

附加图片

**Comment by skilfulwriter** [comment]
![image](https://github.com/user-attachments/assets/15e47e9c-88d9-42a5-adf9-62bf9946e418)
![image](https://github.com/user-attachments/assets/dfaab753-3939-4ddb-829c-2e2bf1ae51d0)
你好，请问下怎么打开呀

**Comment by skilfulwriter** [comment]
![image](https://github.com/user-attachments/assets/2e37e4ff-a19f-4fdb-acaa-e0d535d3ceb0)
![image](https://github.com/user-attachments/assets/3ebcfc1c-85d2-4710-b9db-19bf9e9812dc)
我改了图中所示这个代码，能打开，但是点击登录没反应。改为post,直接打不开，或许有什么我操作失误的地方，请教一下，怎么弄

![image](https://github.com/user-attachments/assets/b3c1887e-f7ba-40ca-9a3b-5ccc71fd1628)
 python3 dirscanmain.py，这个目前是正常的

**Comment by skilfulwriter** [comment]
![image](https://github.com/user-attachments/assets/ce82beb0-9184-4d69-8539-14d77e55b78a)
未捕获引用错误：未定义login_interface_func

**Comment by huan-cdm** [comment]
安装好的虚拟机，可以直接使用：
https://pan.baidu.com/s/19EPOyjgf0JxbbOYymUr2vg?pwd=sufy

**Comment by huan-cdm** [comment]
系统入口：http://ip:port/index/
账号密码在info_scan下的config.py中配置，配置完重新启动下服务；

**Comment by blog2023sunshine** [comment]
> 安装好的虚拟机，可以直接使用： https://pan.baidu.com/s/19EPOyjgf0JxbbOYymUr2vg?pwd=sufy

大佬牛逼，这下可以用的爽了ヘ(~ω~ヘ)

**Comment by ping401** [comment]
请问下这个系统入口在哪儿啊？找不到呢
<img width="459" alt="Snipaste_2024-08-17_10-48-51" src="https://github.com/user-attachments/assets/570000cd-10f7-4fcd-a55f-17d70d2710cb">
<img width="310" alt="Snipaste_2024-08-17_10-48-14" src="https://github.com/user-attachments/assets/02999c20-4c7f-458f-bf1c-46d7189492e0">
<img width="432" alt="Snipaste_2024-08-17_10-46-26" src="https://github.com/user-attachments/assets/13973b38-e588-4946-8728-6d40b67c3647">

**Comment by b2522** [comment]
> 请问下这个系统入口在哪儿啊？找不到呢 <img alt="Snipaste_2024-08-17_10-48-51" width="459" src="https://private-user-images.githubusercontent.com/160581555/358790625-570000cd-10f7-4fcd-a55f-17d70d2710cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjI1LTU3MDAwMGNkLTEwZjctNGZjZC1hNTVmLTE3ZDcwZDI3MTBjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGUwZTFjNDQ1NWFiMDUyZjc3MWFiOTBkNDUwOGQzMDcxMDI4NjdhMjA2MjZmN2ZlNjJhOWUzM2IzYzlmY2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-pcU7SNFwShTv5rjFhJWAazHtwaUxNm0al7DiuL09ww"> <img alt="Snipaste_2024-08-17_10-48-14" width="310" src="https://private-user-images.githubusercontent.com/160581555/358790626-02999c20-4c7f-458f-bf1c-46d7189492e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjI2LTAyOTk5YzIwLTRjN2YtNDU4Zi1iZjFjLTQ2ZDcxODk0OTJlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2E3MGI1NjlkMWZhZDViOTg0NWZmYmZlOWNlMmNhZWFjNjFhYWRiOTgzMTE2NTRiNDUyMjZiYTJhZjM3NDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IjvcTJbkbZDWFImiLVI7HJRJ26lmHk_4B1GdAOdF8P0"> <img alt="Snipaste_2024-08-17_10-46-26" width="432" src="https://private-user-images.githubusercontent.com/160581555/358790630-13973b38-e588-4946-8728-6d40b67c3647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjMwLTEzOTczYjM4LWU1ODgtNDk0Ni04NzI4LTZkNDBiNjdjMzY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTk5YzFkZGM4NjVmZjYwN2Q2ZjAzZTNhZDU2YzZmNTViZGUyOGUwOTZjYmU0Mzg3MDBiNzBiNDFlNzJiZjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.97tZSnxO3aLYbOsc0wKYKGY8a59jrGBZ17mnGhjlj7I"> <img alt="Snipaste_2024-08-17_10-50-17" width="913" src="https://private-user-images.githubusercontent.com/160581555/358790658-6dcf1292-dc0b-49c1-9397-48557bae4df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjU4LTZkY2YxMjkyLWRjMGItNDljMS05Mzk3LTQ4NTU3YmFlNGRmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDJmNTE5MmI1MThjOWU5ZTg2NjI3ODA5MTZkODkwZjQwMWU2YzQ5NTAyODc5M2MyZjI0ZGZmZjdkYzFiZjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lXpQnXEBD3dhhI9a2PSkorqOVBQKVkTTR-WmrdXGo8o">

HTTP://IP:19999/index

**Comment by ping401** [comment]
> > 请问下这个系统入口在哪儿啊？找不到呢 <img alt="Snipaste_2024-08-17_10-48-51" width="459" src="https://private-user-images.githubusercontent.com/160581555/358790625-570000cd-10f7-4fcd-a55f-17d70d2710cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjI1LTU3MDAwMGNkLTEwZjctNGZjZC1hNTVmLTE3ZDcwZDI3MTBjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGUwZTFjNDQ1NWFiMDUyZjc3MWFiOTBkNDUwOGQzMDcxMDI4NjdhMjA2MjZmN2ZlNjJhOWUzM2IzYzlmY2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-pcU7SNFwShTv5rjFhJWAazHtwaUxNm0al7DiuL09ww"> <img alt="Snipaste_2024-08-17_10-48-14" width="310" src="https://private-user-images.githubusercontent.com/160581555/358790626-02999c20-4c7f-458f-bf1c-46d7189492e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjI2LTAyOTk5YzIwLTRjN2YtNDU4Zi1iZjFjLTQ2ZDcxODk0OTJlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2E3MGI1NjlkMWZhZDViOTg0NWZmYmZlOWNlMmNhZWFjNjFhYWRiOTgzMTE2NTRiNDUyMjZiYTJhZjM3NDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IjvcTJbkbZDWFImiLVI7HJRJ26lmHk_4B1GdAOdF8P0"> <img alt="Snipaste_2024-08-17_10-46-26" width="432" src="https://private-user-images.githubusercontent.com/160581555/358790630-13973b38-e588-4946-8728-6d40b67c3647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjMwLTEzOTczYjM4LWU1ODgtNDk0Ni04NzI4LTZkNDBiNjdjMzY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTk5YzFkZGM4NjVmZjYwN2Q2ZjAzZTNhZDU2YzZmNTViZGUyOGUwOTZjYmU0Mzg3MDBiNzBiNDFlNzJiZjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.97tZSnxO3aLYbOsc0wKYKGY8a59jrGBZ17mnGhjlj7I"> <img alt="Snipaste_2024-08-17_10-50-17" width="913" src="https://private-user-images.githubusercontent.com/160581555/358790658-6dcf1292-dc0b-49c1-9397-48557bae4df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODMzOTIsIm5iZiI6MTcyMzg4MzA5MiwicGF0aCI6Ii8xNjA1ODE1NTUvMzU4NzkwNjU4LTZkY2YxMjkyLWRjMGItNDljMS05Mzk3LTQ4NTU3YmFlNGRmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwODI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDJmNTE5MmI1MThjOWU5ZTg2NjI3ODA5MTZkODkwZjQwMWU2YzQ5NTAyODc5M2MyZjI0ZGZmZjdkYzFiZjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lXpQnXEBD3dhhI9a2PSkorqOVBQKVkTTR-WmrdXGo8o">
> 
> [HTTP://IP:19999/index](HTTP://IP:19999/index)

他直接给我跳转到了 http://ip/index

**Comment by huan-cdm** [comment]
![image](https://github.com/user-attachments/assets/913ee320-0fbc-4fdf-98c7-632ac475d5ee)

**Comment by ping401** [comment]
为啥会这样，大佬帮我瞅瞅呢。
<img width="982" alt="Snipaste_2024-08-24_08-26-53" src="https://github.com/user-attachments/assets/4e341ab9-3313-46df-ab2f-d2cdda02541e">
<img width="343" alt="Snipaste_2024-08-24_08-25-09" src="https://github.com/user-attachments/assets/0c263937-c6df-4d7c-8fa3-01c3edd7fa56">
<img width="451" alt="Snipaste_2024-08-24_08-23-23" src="https://github.com/user-attachments/assets/a7c1dcf2-4744-4214-944f-fc0b6a9b32ca">
<img width="492" alt="Snipaste_2024-08-24_08-23-07" src="https://github.com/user-attachments/assets/7ab61296-16e6-4ffc-a6a3-40c91b4d3579">
<img width="455" alt="Snipaste_2024-08-24_08-22-43" src="https://github.com/user-attachments/assets/53fef121-d941-410d-b71b-717c9fdd592e">
<img width="691" alt="Snipaste_2024-08-24_08-20-47" src="https://github.com/user-attachments/assets/6ec3fdcd-8d35-4188-b657-4d81749ce813">

**Comment by ping401** [comment]
> 为啥会这样，大佬帮我瞅瞅呢。 <img alt="Snipaste_2024-08-24_08-26-53" width="982" src="https://private-user-images.githubusercontent.com/160581555/361088807-4e341ab9-3313-46df-ab2f-d2cdda02541e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTk1NTEsIm5iZiI6MTcyNDQ1OTI1MSwicGF0aCI6Ii8xNjA1ODE1NTUvMzYxMDg4ODA3LTRlMzQxYWI5LTMzMTMtNDZkZi1hYjJmLWQyY2RkYTAyNTQxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTgxODUyOWI1M2FlNDhiYjdjNTdmNDc0NjkwNTA2MmMzZTExMzcwOGM4Y2ZhMWRjNGIwOTBhMmY2NmFmZmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.81EVgR32GyAKwVlarMq8WJaiO6YnmYgmjk-H2MgTjXE"> <img alt="Snipaste_2024-08-24_08-25-09" width="343" src="https://private-user-images.githubusercontent.com/160581555/361088813-0c263937-c6df-4d7c-8fa3-01c3edd7fa56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTk1NTEsIm5iZiI6MTcyNDQ1OTI1MSwicGF0aCI6Ii8xNjA1ODE1NTUvMzYxMDg4ODEzLTBjMjYzOTM3LWM2ZGYtNGQ3Yy04ZmEzLTAxYzNlZGQ3ZmE1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWYxZDA5ZmJhZjA1M2NhMDkwMjc0MzlkODc3ZjU4NDc0MDcwOWNkNTQzZjJmNDkyMDExZDI3Yzc2YjIyMzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdJrUh2qAdfoNKF44JUm2DlCTWcDANMQfW8Bi6_dCAU"> <img alt="Snipaste_2024-08-24_08-23-23" width="451" src="https://private-user-images.githubusercontent.com/160581555/361088814-a7c1dcf2-4744-4214-944f-fc0b6a9b32ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTk1NTEsIm5iZiI6MTcyNDQ1OTI1MSwicGF0aCI6Ii8xNjA1ODE1NTUvMzYxMDg4ODE0LWE3YzFkY2YyLTQ3NDQtNDIxNC05NDRmLWZjMGI2YTliMzJjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjBiMzJjYzgxMWVlNWI5YzgwY2E3ZWIwYmIzZGRkYWZlNjA0ODZjYTg0YWUyZTBlOTNmNzVlZmI0YzI4OTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AmZ5N-P8iK7aCeiLaRBiIligtyqiGOre8Gs_NSFlus8"> <img alt="Snipaste_2024-08-24_08-23-07" width="492" src="https://private-user-images.githubusercontent.com/160581555/361088815-7ab61296-16e6-4ffc-a6a3-40c91b4d3579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTk1NTEsIm5iZiI6MTcyNDQ1OTI1MSwicGF0aCI6Ii8xNjA1ODE1NTUvMzYxMDg4ODE1LTdhYjYxMjk2LTE2ZTYtNGZmYy1hNmEzLTQwYzkxYjRkMzU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmVlNmEwMmRmOGU5MTVkZDcxYzZhYWMyNTc0NDZkZjQwODQ4N2RjMDg5ZmRmMmM1YzIwMDA5ZDRmOGE4MzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kU8Y5Lq5_MNqJaQyU0NkbUkvi3Ddb3P0PuuSmnCrxIM"> <img alt="Snipaste_2024-08-24_08-22-43" width="455" src="https://private-user-images.githubusercontent.com/160581555/361088818-53fef121-d941-410d-b71b-717c9fdd592e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTk1NTEsIm5iZiI6MTcyNDQ1OTI1MSwicGF0aCI6Ii8xNjA1ODE1NTUvMzYxMDg4ODE4LTUzZmVmMTIxLWQ5NDEtNDEwZC1iNzFiLTcxN2M5ZmRkNTkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzQ1YzgzMjUxZGZiMDQ0M2E5NzA5N2Y3NmU3OGQ1NjViMTUzMmQ3ZDFmYTRmYjI4NjE2MGZlMWFiYzMwNTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H7bUnhi-DtWHSXx_qug9sGUuHEbPr6sdzbpwt1NrLmo"> <img alt="Snipaste_2024-08-24_08-20-47" width="691" src="https://private-user-images.githubusercontent.com/160581555/361088821-6ec3fdcd-8d35-4188-b657-4d81749ce813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTk1NTEsIm5iZiI6MTcyNDQ1OTI1MSwicGF0aCI6Ii8xNjA1ODE1NTUvMzYxMDg4ODIxLTZlYzNmZGNkLThkMzUtNDE4OC1iNjU3LTRkODE3NDljZTgxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwMDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzE1ODdiYjY5NDY2OTY4YjE1NzQwNjExMDI1YmE3MTE5ODg4NWIxZjA5MmJmM2YzY2YzMDc1MzY2MmJiMjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dMHl66z-ywkWrgi20NbU4e1o989rgGq9otW08NaggSU">

配置没有错啊。访问404

**Comment by ping401** [comment]
输入 ip，点击搜索后，报错。
<img width="824" alt="Snipaste_2024-08-24_09-17-56" src="https://github.com/user-attachments/assets/30540ff3-ff4c-4422-8b26-3a6c21eeb9f0">
<img width="937" alt="Snipaste_2024-08-24_09-17-38" src="https://github.com/user-attachments/assets/7122d46a-82b1-4c81-8651-31d9b07178e5">
