### ISSUE TITLE
尊敬的huan大佬，能否提供一份装好的VMware虚拟机导出文件供我们使用

### ISSUE THREAD

**Issue by blog2023sunshine** [huan-cdm/info_scan#5]
这个系统中python3模块的依赖安装太麻烦了，恳请大佬分享一下安装后导出的虚拟机镜像，万分感谢。
orz

**Comment by huan-cdm** [comment]
开发和测试是在vps上，目前没有虚拟机，后期制作一个发出来；
进入项目目录，执行pip3 install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/  命令安装所需模块；

**Comment by huan-cdm** [comment]
已制作好虚拟机，开箱即用
https://pan.baidu.com/s/19EPOyjgf0JxbbOYymUr2vg?pwd=sufy
