### ISSUE TITLE
采用的虚拟机安装，搜索IP出错

### ISSUE THREAD

**Issue by b2522** [huan-cdm/info_scan#6]
采用的虚拟机安装，IP搜索框后面的搜索点击后出错，archive搜索可以用
Internal Server Error The server encountered an internal error and was unable to complete your request.

**Comment by huan-cdm** [comment]
我本地测没问题，执行bash server_check.sh stopinfoscan 关闭服务，执行python3 scan_main_web.py，输入IP搜索，把shell控制台报错贴出来。
![image](https://github.com/user-attachments/assets/190b8001-8255-44c6-a843-ad9d3632c1a8)

**Comment by b2522** [comment]
按照你的指导，运行python3 scan_main_web.py 没有错误，但在web界面里搜索就是不行
![image](https://github.com/user-attachments/assets/e2283dde-7817-407d-9bce-83138c542f2f)

**Comment by b2522** [comment]
命令行这样也没有结果，是不是超时导致了web页面不行？
![image](https://github.com/user-attachments/assets/c1fbf802-5cb2-414e-8185-8001fc026399)

重新开启服务之后，搜索框依旧不行
![image](https://github.com/user-attachments/assets/fb83ed10-db59-47f2-8ba9-6460c145a247)

![image](https://github.com/user-attachments/assets/8b00b086-b62a-47be-833b-94131458ee02)

**Comment by huan-cdm** [comment]
把1.1.1.1去掉，只运行python3  scan_main_web.py
也有可能是部分接口超时了，将nginx的超时时间调大一些，config.py相关的配置也配置下。
![image](https://github.com/user-attachments/assets/93b51aa4-33c3-4ed2-843b-e72ee9a1e246)

**Comment by b2522** [comment]
时间调大了也不行。config.py里的配置添加了shoda fofa ceye的api，其他没修改。

fofa的搜索好像也不行，感觉搜索功能有点问题。
![image](https://github.com/user-attachments/assets/c2c2cae0-f8cc-46ab-85ff-d905ad494c60)

**Comment by huan-cdm** [comment]
ip搜索也需要配置高德地图api，
fofa搜索确认api接口数量是否用完，并检查网络是否正常。

**Comment by b2522** [comment]
明白了，可能是我的fofa没有api权限导致了错误。

**Comment by huan-cdm** [comment]
克隆最新的代码，修改为可配置多个key，随机调用，未查询到数据返回None，不会直接返回报错。
