### ISSUE TITLE
请问漏洞扫描的IP列表在哪里添加？

### ISSUE THREAD

**Issue by b2522** [huan-cdm/info_scan#7]
请问漏洞扫描的IP列表在哪里添加？
一件扫描能把做个可选列表，自己勾选需要的扫描。

**Comment by huan-cdm** [comment]
一、请问漏洞扫描的IP列表在哪里添加？
第一种：通过fofa搜索，结果直接存入系统
![image](https://github.com/user-attachments/assets/171be1e7-c291-4433-88ac-980bef1a0349)
第二种：直接将url填入文本框，点击添加即可
![image](https://github.com/user-attachments/assets/8678ff94-e0a2-42cf-9453-a6f5dd93c2cd)
二、一件扫描能把做个可选列表，自己勾选需要的扫描？
已加入后期开发计划中

**Comment by b2522** [comment]
添加资产的时候必须带协议头http https，如果只做IP扫描，这个其实不一定需要吧，有点和使用习惯不一样。

在您的指导下，添加资产可以使用了，感谢！

**Comment by huan-cdm** [comment]
http://www.baidu.com
http://127.0.0.1/
https://2.2.2.2/
如果这样格式提交的话，比如端口扫描，系统会自动把ip提出来存入列表中，['127.0.0.1','2.2.2.2']，在进行IP相关扫描
每个扫描器需要的格式不同，有的需要url，有的需要IP，扫描前系统会自动处理进行处理。

**Comment by huan-cdm** [comment]
添加资产的时候必须带协议头http https，如果只做IP扫描，这个其实不一定需要吧，有点和使用习惯不一样。
如果不习惯可以将scan_main_web.py以下代码注释掉，然后重启服务；
![image](https://github.com/user-attachments/assets/b5d931db-407c-4a86-8770-64c222b4f10b)

**Comment by huan-cdm** [comment]
信息收集类工具已开发完可选列表，自己勾选需要的扫描，漏洞扫描类工具正在完善中
![1724146602665](https://github.com/user-attachments/assets/1417edbe-bae7-47a8-903b-78bf2fce806d)
