### ISSUE TITLE
虚拟机无法使用

### ISSUE THREAD

**Issue by HHhne** [huan-cdm/info_scan#8]
root@root:/TIP/info_scan# ./server_check.sh status
infoscan： √
xrayreport： √
urlfinderreport： √
dirscan： √
afrogreport： √

访问80端口，只显示Nginx

com.js已改

**Comment by HHhne** [comment]
![image](https://github.com/user-attachments/assets/c9f9c08c-24ad-43eb-a4d7-9a0b7b8a3080)

**Comment by huan-cdm** [comment]
![image](https://github.com/user-attachments/assets/5b48bd17-1c55-4ac9-ae6e-f381e67d1c21)
