### ISSUE TITLE
虚拟机版本infoscan服务起不来

### ISSUE THREAD

**Issue by xiaoliusec** [huan-cdm/info_scan#9]
手动启动提示80端口占用，和nginx端口冲突，应该改哪个
![image](https://github.com/user-attachments/assets/2b211926-0cf5-44d4-90f0-8c3213bce2eb)

**Comment by huan-cdm** [comment]
修改/TIP/info_scan/scan_main_web.py最后一行的端口
修改/etc/nginx/conf.d/infoscan_nginx.conf第12行，跟上面的端口对应就行
重启nginx和python相关服务
我这边没遇到被占用的情况
